
version: 2

sources:
  - name: b3
    description: "Data from the B3 stock exchange"
    database: financial_data
    schema: raw
    tables:
      - name: b3_financial_transactions
        description: "Raw financial transactions from the B3 stock exchange"
models:
  - name: b3__staging__financial_transactions
    description: "Financial transactions from the B3 stock exchange"
    config:
      schema: staging
  - name: b3__staging__stock_transactions_with_avg_cost
    description: "Stock transactions (buying or selling) from the B3 stock exchange, with the average cost up to that point computed"
    config:
      schema: staging
  - name: b3__staging__products
    description: "Contains all unique product names that show up in B3 transactions. It also generates a common SK products with the same code."
    config:
      schema: staging