financial_data:
  outputs:
    dev:
      dbname: financial_data
      host: localhost
      pass: root
      port: 5433
      schema: public
      threads: 4
      type: postgres
      user: admin
  target: dev
